# Generated by Django 5.1.6 on 2025-02-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LlmModels',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=500)),
                ('model_url', models.EmailField(max_length=1000)),
            ],
        ),
    ]
